# **Data Preparation:**

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data= pd.read_csv("https://raw.githubusercontent.com/rajesh-coventry/Projects/refs/heads/master/00_DataSets/31_E-Commerce%20Shipping%20Data.csv")
data.columns

Index(['ID', 'Warehouse_block', 'Mode_of_Shipment', 'Customer_care_calls',
       'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases',
       'Product_importance', 'Gender', 'Discount_offered', 'Weight_in_gms',
       'Reached.on.Time_Y.N'],
      dtype='object')

In [3]:
data.shape

(10999, 12)

In [4]:
data.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [5]:
data.dtypes

ID                      int64
Warehouse_block        object
Mode_of_Shipment       object
Customer_care_calls     int64
Customer_rating         int64
Cost_of_the_Product     int64
Prior_purchases         int64
Product_importance     object
Gender                 object
Discount_offered        int64
Weight_in_gms           int64
Reached.on.Time_Y.N     int64
dtype: object

In [8]:
# Convert data types to categorycal:
data["Warehouse_block"]= data["Warehouse_block"].astype("category")
data["Mode_of_Shipment"]= data["Mode_of_Shipment"].astype("category")   
data["Product_importance"]= data["Product_importance"].astype("category")
data["Gender"]= data["Gender"].astype("category")

In [9]:
data.dtypes

ID                        int64
Warehouse_block        category
Mode_of_Shipment       category
Customer_care_calls       int64
Customer_rating           int64
Cost_of_the_Product       int64
Prior_purchases           int64
Product_importance     category
Gender                 category
Discount_offered          int64
Weight_in_gms             int64
Reached.on.Time_Y.N       int64
dtype: object

In [10]:
# Check for missing and null values: 
data.isnull().sum().any()

np.False_

In [11]:
# Check for duplicates:
data.duplicated().any()

np.False_

In [14]:
# Count different categories in categorical columns: 
data.select_dtypes(include= "category").value_counts().reset_index()

   Warehouse_block Mode_of_Shipment Product_importance Gender  count
0                F             Ship                low      M    619
1                F             Ship                low      F    580
2                F             Ship             medium      F    575
3                F             Ship             medium      M    508
4                A             Ship                low      F    321
..             ...              ...                ...    ...    ...
85               B           Flight               high      M     12
86               B             Road               high      M     12
87               F           Flight               high      F     11
88               D           Flight               high      F     10
89               D             Road               high      F      7

[90 rows x 5 columns]

In [ ]:
data["Product_importance"].value_counts() # 3 categories

Product_importance
low       5297
medium    4754
high       948
Name: count, dtype: int64

In [ ]:
data["Mode_of_Shipment"].value_counts() # 3 categories

Mode_of_Shipment
Ship      7462
Flight    1777
Road      1760
Name: count, dtype: int64

In [ ]:
data["Warehouse_block"].value_counts() # 5 categories

Warehouse_block
F    3666
D    1834
A    1833
C    1833
B    1833
Name: count, dtype: int64

In [20]:
data["Gender"].value_counts() # 2 categories

Gender
F    5545
M    5454
Name: count, dtype: int64

In [21]:
data.head(3)

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1

In [22]:
# save data in json format:
data.to_json("ecommerce_shipping_data.json")